### PR TITLE
Fix/combobox menu list

### LINKED ISSUE #269: Selecting an option in combobox triggers a page reload
### Prerequisites

- [X] I have [searched](https://github.com/GovTechSG/sgds-govtech-react/issues) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/GovTechSG/sgds-govtech-react/blob/v2/CONTRIBUTING.md)

### Describe the issue

Selecting an option in combobox does not natively come with the e.preventDefault(). This issue also appeared in the DatePicker component when the arrows for the months were clicked, but was resolved in v2.7.2. The e.preventDefault() should come out of the box in the component and we should not need to add this line of code in our app.

https://github.com/user-attachments/assets/51323196-0fb6-4fd7-8384-61865b5ddbeb

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### Describe your frontend stack. What version of React and @govtechsg/sgds-react are you using? CSR or SSR?

NextJS Typescript React

### PR DESCRIPTION
**Pull request by clukhei**
Fixes #269 #271

### CODE REVIEW

File: src/Combobox/Combobox.tsx [hunk 1]
```diff
@@ -84,6 +84,19 @@ const filterIncludes = (inputValue: string, menuList: string[]) => {
...
+  let filteredMenu = []
+  if(filterMethod === "startsWith"){
+    filteredMenu = filterStartsWith(initialValue, menuList)
+  } else if (filterMethod === "includes") {
+    filteredMenu = filterIncludes(initialValue, menuList)
+  } else {
+    filteredMenu = filterMethod(initialValue, menuList)
+  }
+
+  return filteredMenu
```
Comment (th-94) [inline src/Combobox/Combobox.tsx]: I think it's all good, just a comment here for possible code refactor.

```
if(filterMethod === "startsWith"){
   return filterStartsWith(initialValue, menuList);
}

if (filterMethod === "includes") {
   return filterIncludes(initialValue, menuList);
}

return filterMethod(initialValue, menuList);
```

**Review by th-94 — APPROVED** [review]
